// Track D Phase 1 — SubjectLifter interface (Nitro spec) + JS fallback.
//
// The real iOS 17 / Android MLKit subject-lifter is a native HybridObject
// generated by Nitrogen. This TypeScript layer pins the shape so the UI,
// data layer, and tests can move forward before the native module lands.
//
// Behaviour today (JS fallback):
//   - `isSupported()` returns false. UI should fall back to "Use as-is"
//     (no background removal) or a future manual-mask workflow.
//   - `lift(uri)` returns the URI unchanged. CLAUDE.md rule 8 forbids us
//     from inventing alpha pixels with a hash/random fallback — if the
//     native model is unavailable we honestly say "no lift performed".
//
// Once `react-native-nitro-subject-lifter` (or similar) is in place, swap
// the export at the bottom of this file to detect & prefer the native
// implementation:
//
//     export const subjectLifter: SubjectLifter =
//       NativeSubjectLifter.isSupported() ? new NativeSubjectLifter() : jsSubjectLifter;

export type SubjectLifterResult = {
  /** Final image URI. May equal the input URI when the fallback path runs. */
  uri: string;
  width: number;
  height: number;
  /** True iff the lifter produced an image with transparency. */
  hasAlpha: boolean;
};

export interface SubjectLifter {
  isSupported(): boolean;
  lift(imageUri: string): Promise<SubjectLifterResult>;
}

export const jsSubjectLifter: SubjectLifter = {
  isSupported: () => false,
  async lift(uri: string): Promise<SubjectLifterResult> {
    if (!uri || typeof uri !== 'string') {
      throw new Error('subject-lifter: imageUri must be a non-empty string');
    }
    // Intrinsic dimensions need a native image decode. The companion screen
    // calls Image.getSize before persisting, so leave them at 0 here — the
    // store fills them in from the upstream caller's measurement.
    return { uri, width: 0, height: 0, hasAlpha: false };
  },
};

export const subjectLifter: SubjectLifter = jsSubjectLifter;
