//
//  AniseekrSubjectLifter.swift
//  AniSeekr
//
//  On-device background removal (去背) for the companion / pilgrimage overlay.
//  Lifts the foreground subject out of an image and writes a transparent PNG
//  (the "cutout") to the app cache, so the JS layer can place it as a sticker
//  over the live camera preview and bake it into the captured photo.
//
//  Strategy (best → fallback):
//    iOS 17+ : VNGenerateForegroundInstanceMaskRequest — general salient
//              subject segmentation, works for illustrated anime characters.
//    iOS 15+ : VNGeneratePersonSegmentationRequest — person-only, best effort.
//              May not detect illustrated characters; we reject with a clear
//              code so the UI can offer "use as-is" rather than invent pixels
//              (CLAUDE.md rule 8 — never fabricate a mask).
//
//  Exposes to JS (NativeModules.AniseekrSubjectLifter):
//    constant isSupported   : Bool
//    lift(imageUri)         -> { uri, width, height, hasAlpha }
//    liftWithMask(imageUri) -> { maskUri, sourceUri, width, height, hasAlpha }
//      maskUri is a grayscale PNG (white = subject) at exactly the size of the
//      EXIF-normalized original; sourceUri is that normalized original.
//
//  Generated by plugins/with-subject-lifter.js — edit the template under
//  plugins/templates/, not the copy in the Xcode project.
//

import Foundation
import Vision
import CoreImage
import UIKit
import React

@objc(AniseekrSubjectLifter)
class AniseekrSubjectLifter: NSObject {

  private let ciContext = CIContext(options: [.useSoftwareRenderer: false])

  @objc static func requiresMainQueueSetup() -> Bool { return false }

  // Person segmentation is available from iOS 15, so every build at our
  // deployment target (15.1) reports support. The richer iOS 17 path is
  // selected per-call at runtime.
  @objc func constantsToExport() -> [String: Any] {
    return ["isSupported": true]
  }

  // MARK: - Public

  @objc(lift:resolver:rejecter:)
  func lift(_ imageUri: String,
            resolver resolve: @escaping RCTPromiseResolveBlock,
            rejecter reject: @escaping RCTPromiseRejectBlock) {
    // Heavy work off the main thread.
    DispatchQueue.global(qos: .userInitiated).async {
      guard let cgImage = self.loadCGImage(from: imageUri) else {
        reject("decode_failed", "Could not decode image at \(imageUri)", nil)
        return
      }

      do {
        let png: Data
        if #available(iOS 17.0, *) {
          png = try self.liftForegroundInstance(cgImage)
        } else {
          png = try self.liftPerson(cgImage)
        }
        guard let result = self.writeCutout(png) else {
          reject("write_failed", "Could not write cutout PNG to cache", nil)
          return
        }
        resolve(result)
      } catch let LiftError.noSubject(message) {
        reject("no_subject", message, nil)
      } catch {
        reject("lift_failed", error.localizedDescription, error)
      }
    }
  }

  @objc(liftWithMask:resolver:rejecter:)
  func liftWithMask(_ imageUri: String,
                    resolver resolve: @escaping RCTPromiseResolveBlock,
                    rejecter reject: @escaping RCTPromiseRejectBlock) {
    DispatchQueue.global(qos: .userInitiated).async {
      guard let loaded = self.loadNormalizedImage(from: imageUri) else {
        reject("decode_failed", "Could not decode image at \(imageUri)", nil)
        return
      }
      do {
        let maskPNG: Data
        if #available(iOS 17.0, *) {
          maskPNG = try self.foregroundMaskPNG(loaded.cgImage)
        } else {
          maskPNG = try self.personMaskPNG(loaded.cgImage)
        }
        guard let maskURL = self.writeCacheFile(maskPNG, prefix: "subject-mask", ext: "png") else {
          reject("write_failed", "Could not write mask PNG to cache", nil)
          return
        }
        // The mask aligns with the EXIF-normalized pixels; when normalization
        // rotated the image, hand JS a re-encoded copy so Skia (which ignores
        // EXIF) decodes pixels that line up with the mask.
        var sourceUriOut = imageUri
        if loaded.wasRotated {
          guard let jpeg = UIImage(cgImage: loaded.cgImage).jpegData(compressionQuality: 0.95),
                let srcURL = self.writeCacheFile(jpeg, prefix: "subject-source", ext: "jpg") else {
            reject("write_failed", "Could not write normalized source", nil)
            return
          }
          sourceUriOut = srcURL.absoluteString
        }
        resolve([
          "maskUri": maskURL.absoluteString,
          "sourceUri": sourceUriOut,
          "width": loaded.cgImage.width,
          "height": loaded.cgImage.height,
          "hasAlpha": true,
        ])
      } catch let LiftError.noSubject(message) {
        reject("no_subject", message, nil)
      } catch {
        reject("lift_failed", error.localizedDescription, error)
      }
    }
  }

  // MARK: - iOS 17+ foreground instance mask

  @available(iOS 17.0, *)
  private func liftForegroundInstance(_ cgImage: CGImage) throws -> Data {
    let handler = VNImageRequestHandler(cgImage: cgImage, orientation: .up, options: [:])
    let request = VNGenerateForegroundInstanceMaskRequest()
    try handler.perform([request])

    guard let observation = request.results?.first, !observation.allInstances.isEmpty else {
      throw LiftError.noSubject("No subject detected in the image")
    }

    let masked = try observation.generateMaskedImage(
      ofInstances: observation.allInstances,
      from: handler,
      croppedToInstancesExtent: true
    )
    return try pngData(fromPixelBuffer: masked)
  }

  // MARK: - iOS 15/16 person segmentation fallback

  private func liftPerson(_ cgImage: CGImage) throws -> Data {
    let handler = VNImageRequestHandler(cgImage: cgImage, orientation: .up, options: [:])
    let request = VNGeneratePersonSegmentationRequest()
    request.qualityLevel = .accurate
    request.outputPixelFormat = kCVPixelFormatType_OneComponent8
    try handler.perform([request])

    guard let mask = request.results?.first?.pixelBuffer else {
      throw LiftError.noSubject("No person detected in the image")
    }

    let original = CIImage(cgImage: cgImage)
    var maskImage = CIImage(cvPixelBuffer: mask)
    // Person segmentation returns a mask smaller than the source; scale it up
    // to the original extent so alpha lines up with the pixels.
    let scaleX = original.extent.width / maskImage.extent.width
    let scaleY = original.extent.height / maskImage.extent.height
    maskImage = maskImage.transformed(by: CGAffineTransform(scaleX: scaleX, y: scaleY))

    guard let blend = CIFilter(name: "CIBlendWithMask") else {
      throw LiftError.noSubject("Compositor unavailable")
    }
    blend.setValue(original, forKey: kCIInputImageKey)
    // Empty background → transparent everywhere the mask is 0.
    blend.setValue(CIImage.empty(), forKey: kCIInputBackgroundImageKey)
    blend.setValue(maskImage, forKey: "inputMaskImage")

    guard let output = blend.outputImage else {
      throw LiftError.noSubject("Compositing failed")
    }
    let cropped = output.cropped(to: original.extent)
    guard let cg = ciContext.createCGImage(cropped, from: cropped.extent) else {
      throw LiftError.noSubject("Could not render cutout")
    }
    guard let data = UIImage(cgImage: cg).pngData() else {
      throw LiftError.noSubject("Could not encode cutout PNG")
    }
    return data
  }

  // MARK: - Mask generation

  @available(iOS 17.0, *)
  private func foregroundMaskPNG(_ cgImage: CGImage) throws -> Data {
    let handler = VNImageRequestHandler(cgImage: cgImage, orientation: .up, options: [:])
    let request = VNGenerateForegroundInstanceMaskRequest()
    try handler.perform([request])
    guard let observation = request.results?.first, !observation.allInstances.isEmpty else {
      throw LiftError.noSubject("No subject detected in the image")
    }
    let buffer = try observation.generateScaledMaskForImage(
      forInstances: observation.allInstances,
      from: handler
    )
    return try grayscalePNG(
      fromPixelBuffer: buffer,
      targetSize: CGSize(width: cgImage.width, height: cgImage.height)
    )
  }

  private func personMaskPNG(_ cgImage: CGImage) throws -> Data {
    let handler = VNImageRequestHandler(cgImage: cgImage, orientation: .up, options: [:])
    let request = VNGeneratePersonSegmentationRequest()
    request.qualityLevel = .accurate
    request.outputPixelFormat = kCVPixelFormatType_OneComponent8
    try handler.perform([request])
    guard let mask = request.results?.first?.pixelBuffer else {
      throw LiftError.noSubject("No person detected in the image")
    }
    return try grayscalePNG(
      fromPixelBuffer: mask,
      targetSize: CGSize(width: cgImage.width, height: cgImage.height)
    )
  }

  /// Renders a (possibly smaller / float-format) Vision mask buffer to a PNG
  /// scaled to the original's pixel size.
  private func grayscalePNG(fromPixelBuffer buffer: CVPixelBuffer, targetSize: CGSize) throws -> Data {
    var ci = CIImage(cvPixelBuffer: buffer)
    let sx = targetSize.width / ci.extent.width
    let sy = targetSize.height / ci.extent.height
    if abs(sx - 1) > 0.001 || abs(sy - 1) > 0.001 {
      ci = ci.transformed(by: CGAffineTransform(scaleX: sx, y: sy))
    }
    let rect = CGRect(origin: .zero, size: targetSize)
    guard let cg = ciContext.createCGImage(ci, from: rect) else {
      throw LiftError.noSubject("Could not render mask")
    }
    guard let data = UIImage(cgImage: cg).pngData() else {
      throw LiftError.noSubject("Could not encode mask PNG")
    }
    return data
  }

  // MARK: - Helpers

  private enum LiftError: Error {
    case noSubject(String)
  }

  private func writeCacheFile(_ data: Data, prefix: String, ext: String) -> URL? {
    guard let dir = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first
    else { return nil }
    let name = "\(prefix)-\(Int(Date().timeIntervalSince1970 * 1000)).\(ext)"
    let fileURL = dir.appendingPathComponent(name)
    do {
      try data.write(to: fileURL, options: .atomic)
      return fileURL
    } catch {
      return nil
    }
  }

  /// Like loadCGImage, but reports whether EXIF normalization rotated pixels.
  private func loadNormalizedImage(from uri: String) -> (cgImage: CGImage, wasRotated: Bool)? {
    var path = uri
    if let url = URL(string: uri), url.isFileURL {
      path = url.path
    } else if uri.hasPrefix("file://") {
      path = String(uri.dropFirst("file://".count))
    }
    guard let image = UIImage(contentsOfFile: path) else { return nil }
    let wasRotated = image.imageOrientation != .up
    guard let cg = image.normalizedUp().cgImage else { return nil }
    return (cg, wasRotated)
  }

  private func pngData(fromPixelBuffer pixelBuffer: CVPixelBuffer) throws -> Data {
    let ciImage = CIImage(cvPixelBuffer: pixelBuffer)
    guard let cg = ciContext.createCGImage(ciImage, from: ciImage.extent) else {
      throw LiftError.noSubject("Could not render masked image")
    }
    guard let data = UIImage(cgImage: cg).pngData() else {
      throw LiftError.noSubject("Could not encode cutout PNG")
    }
    return data
  }

  private func writeCutout(_ png: Data) -> [String: Any]? {
    let dir = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first
    guard let dir = dir else { return nil }
    let name = "subject-cutout-\(Int(Date().timeIntervalSince1970 * 1000)).png"
    let fileURL = dir.appendingPathComponent(name)
    do {
      try png.write(to: fileURL, options: .atomic)
    } catch {
      return nil
    }
    let image = UIImage(data: png)
    let width = Int(image?.size.width ?? 0)
    let height = Int(image?.size.height ?? 0)
    return [
      "uri": fileURL.absoluteString, // file:// URL
      "width": width,
      "height": height,
      "hasAlpha": true,
    ]
  }

  /// Loads a `file://` (or bare path) image and normalises EXIF orientation to
  /// `.up`, so the cutout isn't rotated relative to what the user picked.
  private func loadCGImage(from uri: String) -> CGImage? {
    var path = uri
    if let url = URL(string: uri), url.isFileURL {
      path = url.path
    } else if uri.hasPrefix("file://") {
      path = String(uri.dropFirst("file://".count))
    }
    guard let image = UIImage(contentsOfFile: path) else { return nil }
    let normalised = image.normalizedUp()
    return normalised.cgImage
  }
}

private extension UIImage {
  /// Redraws the image with `.up` orientation baked in.
  func normalizedUp() -> UIImage {
    if imageOrientation == .up { return self }
    let format = UIGraphicsImageRendererFormat.default()
    format.scale = scale
    let renderer = UIGraphicsImageRenderer(size: size, format: format)
    return renderer.image { _ in
      draw(in: CGRect(origin: .zero, size: size))
    }
  }
}
